name = "sentinel"
main = "src/index.ts"
compatibility_date = "2024-06-01"

[vars]
JWT_EXPIRES_IN = "24h"

[[d1_databases]]
binding = "SENTINEL_DB"
database_name = "sentinel-db"
database_id = "70a71ca7-4b7e-487a-8aa6-46e236c841c7"

[[r2_buckets]]
binding = "SENTINEL_R2"
bucket_name = "sentinel-r2"

[ai]
binding = "AI"

[assets]
directory = "../sentinel-frontend/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"