import { useState, useEffect, useCallback } from 'react';
import { Layout } from '@/components/Layout';
import { dashboardApi, api } from '@/lib/api';
import {
  RefreshCw, Loader2, AlertCircle,
  TrendingUp, Shield, Calendar, Users, FileText, FileSpreadsheet,
} from 'lucide-react';
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer,
  CartesianGrid, PieChart, Pie, Cell, Legend,
} from 'recharts';
import { cn } from '@/lib/utils';

const SEVERITY_COLORS: Record<string, string> = { Critical:'#ef4444', High:'#f97316', Medium:'#f59e0b', Low:'#22c55e' };

function parseUTC(iso: string) { return new Date(iso.includes('Z')||iso.includes('+')?iso:iso+'Z'); }
function fmtDT(iso: string|null) { if(!iso) return '—'; return parseUTC(iso).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}); }

function downloadCSV(filename: string, headers: string[], rows: string[]) {
  const csv = [headers.join(','), ...rows].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

function downloadPDF(title: string, tableHeaders: string[], tableRows: string[][], meta: string) {
  const rows = tableRows.map(r => `<tr>${r.map(c=>`<td>${c??'—'}</td>`).join('')}</tr>`).join('');
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>${title}</title>
<style>
body{font-family:Arial,sans-serif;font-size:11px;margin:20px;color:#1a1a2e}
.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;padding-bottom:10px;border-bottom:2px solid #1e3a5f}
h1{font-size:18px;color:#1e3a5f;margin:0}
.meta{font-size:10px;color:#666}
table{width:100%;border-collapse:collapse;margin-top:12px}
th{background:#1e3a5f;color:white;padding:7px 8px;text-align:left;font-size:10px}
td{padding:6px 8px;border-bottom:1px solid #e2e8f0;font-size:10px}
tr:nth-child(even) td{background:#f8fafc}
.footer{margin-top:20px;font-size:10px;color:#94a3b8;text-align:center}
@media print{body{margin:0}}
</style></head><body>
<div class="header"><div><h1>🛡 Sentinel Guard — ${title}</h1><div class="meta">${meta}</div></div>
<div class="meta">ITC ICML, Khordha · ${new Date().toLocaleString('en-IN',{hour12:false})}</div></div>
<table><thead><tr>${tableHeaders.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table>
<div class="footer">Generated by Sentinel Guard · Confidential</div></body></html>`;
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  win?.addEventListener('load', () => { win.print(); URL.revokeObjectURL(url); });
}

async function imageUrlToBase64(url: string): Promise<string|null> {
  try {
    const token = localStorage.getItem('sentinel_token');
    const res = await fetch(url, { headers: token ? { Authorization: `Bearer ${token}` } : undefined });
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise(resolve => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch { return null; }
}

async function downloadIncidentsWithPhotosPDF(incidents: any[]) {
  const withPhotos = await Promise.all(incidents.map(async (i) => ({ ...i, photo_b64: i.photo_url ? await imageUrlToBase64(i.photo_url) : null })));
  const cards = withPhotos.map(i => `
    <div class="incident-card">
      <div class="incident-header">
        <div><b>#${i.id} — ${i.title}</b><br/><small>${i.category} · ${fmtDT(i.reported_at)}</small></div>
        <span class="badge sev-${i.severity}">${i.severity}</span>
      </div>
      <table class="meta-table">
        <tr><td>Status</td><td>${i.status}</td></tr>
        <tr><td>Guard</td><td>${i.guard_name||'—'}</td></tr>
        ${i.resolution_notes ? `<tr><td>Resolution</td><td>${i.resolution_notes}</td></tr>` : ''}
      </table>
      ${i.photo_b64 ? `<img class="incident-photo" src="${i.photo_b64}"/>` : ''}
    </div>`).join('');
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Critical Incidents Report</title>
<style>
body{font-family:Arial,sans-serif;font-size:12px;margin:20px;color:#1a1a2e}
.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;padding-bottom:10px;border-bottom:2px solid #1e3a5f}
h1{font-size:18px;color:#1e3a5f;margin:0}
.meta{font-size:10px;color:#666}
.incident-card{border:1px solid #e2e8f0;border-radius:8px;padding:12px;margin-bottom:14px;page-break-inside:avoid}
.incident-header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:8px}
.badge{padding:3px 10px;border-radius:12px;font-size:10px;font-weight:700;white-space:nowrap}
.sev-Critical{background:#fee2e2;color:#991b1b}.sev-High{background:#ffedd5;color:#9a3412}
.sev-Medium{background:#fef3c7;color:#92400e}.sev-Low{background:#dcfce7;color:#166534}
.meta-table{width:100%;font-size:10px;margin-top:6px}
.meta-table td{padding:2px 6px}
.meta-table td:first-child{color:#94a3b8;width:100px}
.incident-photo{max-width:280px;max-height:200px;margin-top:8px;border-radius:6px;border:1px solid #e2e8f0}
.footer{margin-top:20px;font-size:10px;color:#94a3b8;text-align:center}
@media print{body{margin:0}}
</style></head><body>
<div class="header"><div><h1>🛡 Sentinel Guard — Critical Incidents Report</h1><div class="meta">Total: ${incidents.length} critical incidents</div></div>
<div class="meta">ITC ICML, Khordha · ${new Date().toLocaleString('en-IN',{hour12:false})}</div></div>
${cards}
<div class="footer">Generated by Sentinel Guard · Confidential</div></body></html>`;
  const blob2 = new Blob([html], { type: 'text/html' });
  const url2 = URL.createObjectURL(blob2);
  const win2 = window.open(url2, '_blank');
  win2?.addEventListener('load', () => { win2.print(); URL.revokeObjectURL(url2); });
}

type ReportType = 'daily'|'shift'|'weekly'|'monthly'|'critical'|'audit_trail';
const REPORT_TYPES = [
  { type:'daily' as ReportType, label:'Daily Report', icon:Calendar, desc:"Today's patrol & incident summary", color:'text-blue-600 bg-blue-50' },
  { type:'shift' as ReportType, label:'Shift Report', icon:Users, desc:'Breakdown by Shift A / B / C', color:'text-green-600 bg-green-50' },
  { type:'weekly' as ReportType, label:'Weekly Report', icon:TrendingUp, desc:'Last 7 days patrol compliance', color:'text-purple-600 bg-purple-50' },
  { type:'monthly' as ReportType, label:'Monthly Report', icon:TrendingUp, desc:'Last 30 days full summary', color:'text-amber-600 bg-amber-50' },
  { type:'critical' as ReportType, label:'Critical Incidents', icon:AlertCircle, desc:'All Critical/Escalated incidents', color:'text-red-600 bg-red-50' },
  { type:'audit_trail' as ReportType, label:'Audit Trail', icon:Shield, desc:'Login, scan and action logs', color:'text-gray-600 bg-gray-50' },
];

export default function Reports() {
  const [patrolStats, setPatrolStats]     = useState<any>(null);
  const [incidentStats, setIncidentStats] = useState<any>(null);
  const [guardPerf, setGuardPerf]         = useState<any>(null);
  const [loading, setLoading]             = useState(true);
  const [error, setError]                 = useState('');
  const [days, setDays]                   = useState(7);
  const [generating, setGenerating]       = useState<ReportType|null>(null);

  const load = useCallback(() => {
    setLoading(true); setError('');
    Promise.all([
      dashboardApi.patrolStats(days) as Promise<any>,
      dashboardApi.incidentStats(days) as Promise<any>,
      dashboardApi.guardPerformance(days) as Promise<any>,
    ]).then(([p,i,g])=>{setPatrolStats(p);setIncidentStats(i);setGuardPerf(g);})
      .catch((e: Error)=>setError(e.message)).finally(()=>setLoading(false));
  }, [days]);
  useEffect(()=>{load();}, [load]);

  const chartData = (patrolStats?.by_day || []).map((d: any) => ({
    name: parseUTC(d.date).toLocaleDateString('en',{weekday:'short',day:'numeric'}),
    Completed: d.completed, Missed: d.missed,
  }));
  const incidentBySeverity = (incidentStats?.by_severity || []).map((s: any) => ({ name:s.severity, value:s.count, fill:SEVERITY_COLORS[s.severity]||'#94a3b8' }));
  const guards = guardPerf?.guards || [];

  async function handleGenerate(type: ReportType, format: 'pdf'|'csv') {
    setGenerating(type);
    try {
      const now = new Date().toISOString().slice(0,10);
      if (type === 'daily') {
        const d = await (api.get as any)(`/patrols?limit=100&date=${now}`);
        const patrols = d.patrols || [];
        if (format === 'csv') {
          downloadCSV(`Daily_Report_${now}.csv`, ['Patrol ID','Guard','Employee ID','Shift','Status','Start Time','End Time'],
            patrols.map((p:any)=>[p.id,p.guard_name,p.guard_employee_id,p.shift||'—',p.status,fmtDT(p.actual_start),fmtDT(p.actual_end)].join(',')));
        } else {
          downloadPDF('Daily Patrol Report', ['#','Guard','Employee ID','Shift','Status','Start','End'],
            patrols.map((p:any)=>[p.id,p.guard_name,p.guard_employee_id,p.shift||'—',p.status,fmtDT(p.actual_start),fmtDT(p.actual_end)]),
            `Date: ${now} · Total patrols: ${patrols.length}`);
        }
      } else if (type === 'shift') {
        const d: any = await (dashboardApi.shiftCompliance as any)(days);
        const shifts = d.shift_compliance || [];
        if (format === 'csv') {
          downloadCSV(`Shift_Report_${now}.csv`, ['Shift','Completed','Missed','Compliance %'],
            shifts.map((s:any)=>[s.shift,s.completed,s.missed,s.compliance_pct].join(',')));
        } else {
          downloadPDF('Shift Compliance Report', ['Shift','Completed','Missed','Compliance %'],
            shifts.map((s:any)=>[`Shift ${s.shift}`,s.completed,s.missed,`${s.compliance_pct}%`]), `Period: Last ${days} days`);
        }
      } else if (type === 'weekly' || type === 'monthly') {
        const d: any = days === 7 && type==='weekly' ? patrolStats : await (dashboardApi.patrolStats as any)(type==='monthly'?30:7);
        const byDay = d?.by_day || [];
        if (format === 'csv') {
          downloadCSV(`${type==='monthly'?'Monthly':'Weekly'}_Report_${now}.csv`, ['Date','Completed','Missed','Total'],
            byDay.map((r:any)=>[r.date,r.completed,r.missed,r.completed+r.missed].join(',')));
        } else {
          downloadPDF(`${type==='monthly'?'Monthly':'Weekly'} Patrol Report`, ['Date','Completed','Missed','Total'],
            byDay.map((r:any)=>[r.date,r.completed,r.missed,r.completed+r.missed]), `Period: Last ${type==='monthly'?30:7} days`);
        }
      } else if (type === 'critical') {
        const d = await (api.get as any)('/incidents?severity=Critical&limit=200');
        const incidents = d.incidents || [];
        if (format === 'csv') {
          downloadCSV(`Critical_Incidents_${now}.csv`, ['ID','Title','Category','Severity','Status','Guard','Reported At'],
            incidents.map((i:any)=>[i.id,`"${i.title}"`,i.category,i.severity,i.status,i.guard_name||'—',fmtDT(i.reported_at)].join(',')));
        } else {
          await downloadIncidentsWithPhotosPDF(incidents);
        }
      } else if (type === 'audit_trail') {
        const d: any = await (dashboardApi as any).auditTrail();
        const logs = d.logs || [];
        if (format === 'csv') {
          downloadCSV(`Audit_Trail_${now}.csv`, ['ID','Action','Description','User','IP','Timestamp'],
            logs.map((l:any)=>[l.id,l.action,`"${l.description||''}"`,l.user_name||'—',l.ip_address||'—',fmtDT(l.created_at)].join(',')));
        } else {
          downloadPDF('Audit Trail', ['ID','Action','User','Description','Timestamp'],
            logs.map((l:any)=>[l.id,l.action,l.user_name||'—',(l.description||'').slice(0,60),fmtDT(l.created_at)]), `Total: ${logs.length} audit entries`);
        }
      }
    } catch (e: any) { alert(`Export failed: ${e.message}`); }
    finally { setGenerating(null); }
  }

  return (
    <Layout>
      <header className="mb-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div><h2 className="text-2xl font-semibold text-primary">Reports</h2><p className="text-text-muted text-sm">Download patrol and incident reports as PDF or Excel.</p></div>
        <div className="flex items-center gap-2">
          {[7,14,30].map(d=>(
            <button key={d} onClick={()=>setDays(d)} className={cn('px-3 py-1.5 rounded-md text-xs font-medium border transition-colors', days===d?'bg-accent text-white border-accent':'bg-surface-alt text-text-muted border-border hover:border-accent/40')}>{d}d</button>
          ))}
          <button onClick={load} className="p-2 rounded-lg border border-border hover:bg-surface transition-colors text-text-muted"><RefreshCw size={15} className={loading?'animate-spin':''}/></button>
        </div>
      </header>

      {error && <div className="flex items-center gap-2 p-3 mb-4 rounded-lg bg-danger/10 text-danger text-sm"><AlertCircle size={15}/> {error}</div>}

      <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-8">
        {REPORT_TYPES.map(rt=>(
          <div key={rt.type} className="p-4 rounded-xl border border-border bg-white hover:shadow-md transition-all">
            <div className="flex items-center gap-3 mb-3">
              <div className={cn('p-2 rounded-lg', rt.color)}><rt.icon size={18}/></div>
              <div><p className="text-sm font-semibold text-primary">{rt.label}</p><p className="text-xs text-text-muted">{rt.desc}</p></div>
            </div>
            <div className="flex gap-2">
              <button onClick={()=>handleGenerate(rt.type,'pdf')} disabled={generating===rt.type}
                className="flex-1 flex items-center justify-center gap-1.5 py-2 rounded-lg bg-red-50 border border-red-200 text-red-700 text-xs font-medium hover:bg-red-100 transition-colors disabled:opacity-50">
                {generating===rt.type ? <Loader2 size={12} className="animate-spin"/> : <FileText size={12}/>} PDF
              </button>
              <button onClick={()=>handleGenerate(rt.type,'csv')} disabled={generating===rt.type}
                className="flex-1 flex items-center justify-center gap-1.5 py-2 rounded-lg bg-green-50 border border-green-200 text-green-700 text-xs font-medium hover:bg-green-100 transition-colors disabled:opacity-50">
                {generating===rt.type ? <Loader2 size={12} className="animate-spin"/> : <FileSpreadsheet size={12}/>} Excel
              </button>
            </div>
          </div>
        ))}
      </section>

      <section className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
        <div className="lg:col-span-2 p-4 rounded-xl border border-border bg-white">
          <h3 className="text-sm font-semibold text-primary mb-4">Patrol Activity — Last {days} Days</h3>
          {chartData.length > 0 ? (
            <div className="h-56"><ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData} barGap={4}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0"/>
                <XAxis dataKey="name" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip/>
                <Legend wrapperStyle={{fontSize:12}}/>
                <Bar dataKey="Completed" fill="#3b82f6" radius={[4,4,0,0]}/>
                <Bar dataKey="Missed" fill="#ef4444" radius={[4,4,0,0]}/>
              </BarChart>
            </ResponsiveContainer></div>
          ) : <div className="h-56 flex items-center justify-center text-text-muted text-sm">{loading?<Loader2 size={18} className="animate-spin"/>:'No patrol data'}</div>}
        </div>
        <div className="p-4 rounded-xl border border-border bg-white">
          <h3 className="text-sm font-semibold text-primary mb-4">Incidents by Severity</h3>
          {incidentBySeverity.length > 0 ? (
            <div className="h-56"><ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie data={incidentBySeverity} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={80} label={({name,value}:any)=>`${name}: ${value}`}>
                  {incidentBySeverity.map((entry:any,i:number)=><Cell key={i} fill={entry.fill}/>)}
                </Pie><Tooltip/>
              </PieChart>
            </ResponsiveContainer></div>
          ) : <div className="h-56 flex items-center justify-center text-text-muted text-sm">{loading?<Loader2 size={18} className="animate-spin"/>:'No incident data'}</div>}
        </div>
      </section>

      {guards.length > 0 && (
        <div className="p-4 rounded-xl border border-border bg-white">
          <h3 className="text-sm font-semibold text-primary mb-4">Guard Performance — Last {days} Days</h3>
          <div className="overflow-x-auto"><table className="w-full text-sm min-w-[500px]">
            <thead className="bg-gray-50 border-b border-border"><tr>{['Guard','Employee ID','Patrols','Completed','Compliance %'].map(h=><th key={h} className="text-left px-3 py-2 text-xs font-semibold text-text-muted">{h}</th>)}</tr></thead>
            <tbody className="divide-y divide-border">
              {guards.map((g:any)=>(
                <tr key={g.id} className="hover:bg-gray-50">
                  <td className="px-3 py-2.5 text-xs font-medium text-primary">{g.full_name}</td>
                  <td className="px-3 py-2.5 text-xs text-text-muted">{g.employee_id}</td>
                  <td className="px-3 py-2.5 text-xs text-text-muted">{g.total_patrols}</td>
                  <td className="px-3 py-2.5 text-xs text-text-muted">{g.completed_patrols}</td>
                  <td className="px-3 py-2.5"><div className="flex items-center gap-2"><div className="flex-1 h-1.5 rounded-full bg-gray-200 max-w-16"><div className="h-full rounded-full bg-accent" style={{width:`${g.completion_rate}%`}}/></div><span className="text-xs font-medium text-primary">{g.completion_rate}%</span></div></td>
                </tr>
              ))}
            </tbody>
          </table></div>
        </div>
      )}
    </Layout>
  );
}
